---
- name: PING SINGLE HOST | Async wait for ping command to finish
  async_status:
    jid: "{{ ping_single_host_job.ansible_job_id }}"
  register: _ping_job
  until: _ping_job.finished
  delay: 10  # Check every 10 seconds
  retries: 10  # Retry up to 10 times
  changed_when: false
  failed_when: false

- name: PING SINGLE HOST | Remove async job results file
  ansible.builtin.file:
    path: "{{ _ping_job.results_file }}"
    state: absent

# - debug:
#     var: _ping_job

- name: PING SINGLE HOST | Split output lines
  ansible.builtin.set_fact:
    ping_splitted_results:
      statistics: "{{ _ping_job.stdout_lines[3].split(',') }}"
      timings: "{{ _ping_job.stdout_lines[4].split('=') }}"
      reachable: "{{ (_ping_job.rc | int == 0) | bool }}"

# - debug:
#     var: ping_splitted_results

- name: PING SINGLE HOST | Extract statistics and timings if device is reachable
  ansible.builtin.set_fact:
    ping_results:
      device_ip: "{{ ping_single_host_job.host_ip }}"
      protocol: "icmp"
      packets:
        transmitted: "{{ ping_splitted_results.statistics[0].split(' ')[0] | trim }}"
        received: "{{ ping_splitted_results.statistics[1].split(' ')[1] | trim }}"
        loss: "{{ ping_splitted_results.statistics[2].split(' ')[1] | trim | replace('%', '') }}"
        time: "{{ ping_splitted_results.statistics[3].split(' ')[2] | trim | replace('ms', '') }}"
      rtt:
        min: "{{ ping_splitted_results.timings[1].split('/')[0] | trim }}"
        avg: "{{ ping_splitted_results.timings[1].split('/')[1] | trim }}"
        max: "{{ ping_splitted_results.timings[1].split('/')[2] | trim }}"
      reachable: true
  when:
    - ping_splitted_results.reachable

- name: PING SINGLE HOST | Mark device as Unreachable
  ansible.builtin.set_fact:
    ping_results:
      device_ip: "{{ ping_single_host_job.host_ip }}"
      protocol: "icmp"
      packets:
        transmitted: "{{ ping_count }}"
        received: "0"
        loss: "100"
        time: "0"
      rtt:
        min: "0"
        avg: "0"
        max: "0"
      reachable: false
  when:
    - not ping_splitted_results.reachable

- name: PING SINGLE HOST | Output results to log
  debug:
    var: ping_results
